port: /dev/ttyScan1
baud: 500000
laser_frequency: 25
inverted: true
scan_id: 7
frame_id: /base_laser_front_link
scan_intervals: [[115, 426]] #including borders, these intervals are included to the scan
