port: /dev/ttyScan0
baud: 500000
laser_frequency: 25
inverted: true
scan_id: 8
frame_id: /base_laser_rear_link
scan_intervals: [[115, 426]] #including borders, these intervals are included to the scan
