<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find cob_description)/urdf/cob4_base/base.gazebo.xacro" />

  <!-- drive_wheel module -->
  <xacro:include filename="$(find cob_description)/urdf/drive_wheel/drive_wheel.urdf.xacro" />

  <!-- sensors -->
  <xacro:include filename="$(find cob_description)/urdf/sensors/sick_s300_laser.urdf.xacro"/>

  <!-- properties -->
  <property name="caster_offset_x" value="0.24844" />  <!--modify here-->
  <property name="caster_offset_y" value="0.21515" />
  <property name="caster_offset_z" value="0.08" />

  <property name="base_mass" value="50" />


  <xacro:macro name="base" params="name use_old_joint_names">

    <link name="${name}_footprint"/>

    <joint name="${name}_footprint_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${name}_footprint"/>
      <child link="${name}_link" />
    </joint>

    <link name="${name}_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${base_mass}" />
        <inertia ixx="5.652232699207" ixy="-0.009719934438" ixz="1.293988226423"
             iyy="5.669473158652" iyz="-0.007379583694" izz="3.683196351726" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />  
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_base/base.dae"/>
          <!--box size="0.01 0.01 0.01" /-->
        </geometry> 
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_base/base_collision.stl"/>
          <!--box size="0.01 0.01 0.01" /-->
        </geometry>
      </collision>
    </link>


    <!-- arrangement of the three drive_wheel modules -->
    <xacro:if value="${use_old_joint_names}">
      <xacro:drive_wheel parent="${name}_link" suffix="fl" >
        <origin xyz="${caster_offset_x/2} ${caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
      </xacro:drive_wheel>
      <xacro:drive_wheel parent="${name}_link" suffix="bl" >
        <origin xyz="${-caster_offset_x} 0.0 ${caster_offset_z}" rpy="0 0 0" />
      </xacro:drive_wheel>
      <xacro:drive_wheel parent="${name}_link" suffix="br" >
        <origin xyz="${caster_offset_x/2} ${-caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
      </xacro:drive_wheel>
    </xacro:if>

    <xacro:unless value="${use_old_joint_names}">
      <xacro:drive_wheel parent="${name}_link" suffix="fl" >
        <origin xyz="${caster_offset_x/2} ${caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
      </xacro:drive_wheel>
      <xacro:drive_wheel parent="${name}_link" suffix="b" >
        <origin xyz="${-caster_offset_x} 0.0 ${caster_offset_z}" rpy="0 0 0" />
      </xacro:drive_wheel>
      <xacro:drive_wheel parent="${name}_link" suffix="fr" >
        <origin xyz="${caster_offset_x/2} ${-caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
      </xacro:drive_wheel>
    </xacro:unless>


    <!-- sensors -->
    <xacro:sick_s300_laser_v0 name="${name}_laser_front" parent="${name}" ros_topic="scan_front_raw" update_rate="12" min_angle="-2.094" max_angle="2.094" >
      <origin xyz="${laser_front_x} ${laser_front_y} ${laser_front_z}" rpy="${laser_front_roll} ${laser_front_pitch} ${laser_front_yaw}" />
    </xacro:sick_s300_laser_v0>

    <xacro:sick_s300_laser_v0 name="${name}_laser_left" parent="${name}" ros_topic="scan_left_raw" update_rate="12" min_angle="-2.094" max_angle="2.094" >
      <origin xyz="${laser_left_x} ${laser_left_y} ${laser_left_z}" rpy="${laser_left_roll} ${laser_left_pitch} ${laser_left_yaw}" />
    </xacro:sick_s300_laser_v0>

    <xacro:sick_s300_laser_v0 name="${name}_laser_right" parent="${name}" ros_topic="scan_right_raw" update_rate="12" min_angle="-2.094" max_angle="2.094" >
      <origin xyz="${laser_right_x} ${laser_right_y} ${laser_right_z}" rpy="${laser_right_roll} ${laser_right_pitch} ${laser_right_yaw}" />
    </xacro:sick_s300_laser_v0>


    <!-- gazebo extensions -->
    <xacro:base_gazebo name="${name}" />

  </xacro:macro>

</robot>
