Header header

#number of desired solutions
uint32 num_solutions

# the IK request; this contains the TCP_goal_position
kinematics_msgs/PositionIKRequest ik_request

# Maximum allowed time for IK calculation
duration timeout

---
#array of found solution
cob_msgs/FullIKSolution[] full_ik_solutions

#### some additional information ####
std_msgs/Bool success
std_msgs/String error_message
