Header header
bool has_wireless_emstop
bool has_fall_sensors
bool has_magnetic_safety_switch

bool ack_needed
bool emergency_button_stop
bool brake_button_stop
bool laser_stop
bool wireless_stop
bool fall_sensor_stop
bool external_stop

bool laser_bridged
bool wireless_bridged

bool magnetic_safety_switch

bool laser_front_ok
bool laser_left_ok
bool laser_right_ok

bool fall_sensor_front
bool fall_sensor_left
bool fall_sensor_right
bool fall_sensor_released

bool base_active
bool torso_active
bool base_enabled
bool torso_enabled
