<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="safety_offset" value="0.02"/>

  <xacro:include filename="$(find cob_description)/urdf/common.xacro" />
  <xacro:include filename="$(find cob_description)/urdf/cob4_arm/cob4_arm.gazebo.xacro" />
  <xacro:include filename="$(find cob_description)/urdf/cob4_arm/cob4_arm.transmission.xacro" />

  <xacro:macro name="cob4_arm" params="parent name *origin has_podest">

    <xacro:if value="${has_podest}">
      <!-- joint between base_link and cob4_arm_connector_link -->
      <joint name="${name}_podest_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${name}_podest_link"/>
      </joint>
      <link name="${name}_podest_link">
        <xacro:default_inertial/>
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <cylinder radius="0.03" length="0.05"/>
          </geometry>
        </visual>

        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <cylinder radius="0.03" length="0.05"/>
          </geometry>
        </collision>
      </link>

      <joint name="${name}_base_joint" type="fixed">
        <origin xyz="0 0 0.025" rpy="0 0 0" />
        <parent link="${name}_podest_link"/>
        <child link="${name}_base_link"/>
      </joint>
    </xacro:if>

    <xacro:unless value="${has_podest}">
      <!-- joint between base_link and cob4_arm_connector_link -->
      <joint name="${name}_base_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${name}_base_link"/>
      </joint>
    </xacro:unless>



    <!-- static part of PRL100 -->
    <link name="${name}_base_link">
      <xacro:default_inertial/>
  <!--
      <xacro:cylinder_inertial radius="0.056" length="0.12" mass="2.0">
        <origin xyz="0 0 ${0.12/2}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
  -->
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_arm/arm_base_link.stl" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_arm/arm_base_link.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_base_link and arm_1_link -->
    <joint name="${name}_1_joint" type="revolute">
      <origin xyz="0 0 0.139" rpy="0 0 0" />
      <parent link="${name}_base_link"/>
      <child link="${name}_1_link" />
      <axis xyz="0 0 1"/>
      <dynamics damping="0" friction="0"/>
      <limit effort="81.5" velocity="0.66" lower="${-4.71 + safety_offset}" upper="${4.71 - safety_offset}"/>   <!--Theoretical limit +/-270 , Real Limit +/- 270-->
      <!--safety_controller k_position="20" k_velocity="50" soft_lower_limit="${-M_PI + 0.01}" soft_upper_limit="${M_PI - 0.01}" /-->
    </joint>

    <!-- prl100 rotor + shoulder flansh -->
    <link name="${name}_1_link">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0.0 0.0662 0.0473" rpy="0 0 0"/>
        <mass value="0.8"/>
        <inertia ixx="0.002034" ixy="0.0" ixz="0.0" iyy="0.001437" iyz="0.000784" izz="0.00161" />
      </inertial>
-->
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_arm/arm_1_link.dae" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_arm/arm_1_collision.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_1_link and arm_2_link -->
    <joint name="${name}_2_joint" type="revolute">
      <origin xyz="0 0 0.0915" rpy="${M_PI/2} 0 0"/>
      <parent link="${name}_1_link"/>
      <child link="${name}_2_link"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0" friction="0"/>
      <limit effort="48" velocity="1.57" lower="${-1.91 + safety_offset}" upper="${1.91 - safety_offset}"/>   <!--Theoretical limit +/-170 , Real Limit +/- 110 (self collision)-->
      <!--safety_controller k_position="20" k_velocity="50" soft_lower_limit="${-2.0943 + 0.01}" soft_upper_limit="${2.0943 - 0.01}" /-->
    </joint>

    <link name="${name}_2_link">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0.018 -0.018" rpy="0 0 0"/>
        <mass value="3.9"/>
        <inertia ixx="0.009780" ixy="0.0" ixz="0.0" iyy="0.013300" iyz="0.0" izz="0.009780" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_arm/arm_2_link.dae" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_arm/arm_2_collision.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_2_link and arm_3_link -->
    <joint name="${name}_3_joint" type="revolute">
      <origin xyz="0 0 0" rpy="-${M_PI/2} 0 0"/>
      <parent link="${name}_2_link"/>
      <child link="${name}_3_link"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0" friction="0"/>
      <limit effort="48" velocity="1.57" lower="${-2.96 + safety_offset}" upper="${2.96 - safety_offset}"/>   <!--Theoretical limit +/-170 , Real Limit +/- 170-->
      <!--safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-M_PI + 0.01}" soft_upper_limit="${M_PI - 0.01}" /-->
    </joint>

    <link name="${name}_3_link">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0.0 0.06247 0.23425" rpy="0 0 0"/>
        <mass value="1.94533"/>
        <inertia ixx="0.0344" ixy="0.0" ixz="0.0077" iyy="0.0362" iyz="0.0" izz="0.0052" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_arm/arm_3_link.dae" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_arm/arm_3_collision.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_3_link and arm_4_link -->
    <joint name="${name}_4_joint" type="revolute">
      <origin xyz="0 0 0.45360" rpy="${M_PI/2} 0 0" />
      <parent link="${name}_3_link"/>
      <child link="${name}_4_link"/>
      <axis xyz="0 0 1" />
      <dynamics damping="0" friction="0"/>
      <limit effort="48" velocity="1.57" lower="${-2.61 + safety_offset}" upper="${2.61 - safety_offset}"/>   <!--Theoretical limit +/-170 , Real Limit +/- 150 (self collision)-->
      <!--safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-2.0943951 + 0.01}" soft_upper_limit="${2.0943951 - 0.01}" /-->
    </joint>

    <link name="${name}_4_link">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0.018 -0.018" rpy="0 0 0"/>
        <mass value="3.9"/>
        <inertia ixx="0.009780" ixy="0.0" ixz="0.0" iyy="0.013300" iyz="0.0" izz="0.009780" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_arm/arm_4_link.dae" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_arm/arm_4_collision.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_4_link and arm_5_link -->
    <joint name="${name}_5_joint" type="revolute">
      <origin xyz="0 0 0" rpy="-${M_PI/2} 0 0" />
      <parent link="${name}_4_link"/>
      <child link="${name}_5_link"/>
      <axis xyz="0 0 1" />
      <dynamics damping="0" friction="0"/>
      <limit effort="48" velocity="1.57" lower="${-2.96 + safety_offset}" upper="${2.96 - safety_offset}"/>   <!--Theoretical limit +/-170 , Real Limit +/- 170-->
      <!--safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-M_PI + 0.01}" soft_upper_limit="${M_PI - 0.01}" /-->
    </joint>

    <link name="${name}_5_link">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0.0 0.04175 0.17026" rpy="0 0 0"/>
        <mass value="1.3297"/>
        <inertia ixx="0.01" ixy="0.0" ixz="-0.0031" iyy="0.0111" iyz="0.0" izz="0.0031" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_arm/arm_5_link.dae" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_arm/arm_5_collision.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_5_link and arm_6_link -->
    <joint name="${name}_6_joint" type="revolute">
      <origin xyz="0 0 0.2986" rpy="${M_PI/2} 0 0" />
      <parent link="${name}_5_link"/>
      <child link="${name}_6_link"/>
      <axis xyz="0 0 1" />
      <dynamics damping="0" friction="0"/>
      <limit effort="15" velocity="2.09" lower="${-2.96 + safety_offset}" upper="${2.96 - safety_offset}"/>   <!--Theoretical limit +/-170 , Real Limit -140/+170 (self collision)-->
      <!--safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-2.0943951 + 0.01}" soft_upper_limit="${2.0943951 - 0.01}" /-->
    </joint>

    <link name="${name}_6_link">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0.012 -0.012" rpy="0 0 0"/>
        <mass value="1.9"/>
        <inertia ixx="0.002750" ixy="0.0" ixz="0.0" iyy="0.004002" iyz="0.0" izz="0.002830" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_arm/arm_6_link.dae" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cob_description/meshes/cob4_arm/arm_6_collision.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_6_link and arm_7_link -->
    <joint name="${name}_7_joint" type="revolute">
      <origin xyz="0 0 0" rpy="-${M_PI/2} 0 0" />
      <parent link="${name}_6_link"/>
      <child link="${name}_7_link"/>
      <axis xyz="0 0 1" />
      <dynamics damping="0" friction="0"/>
      <limit effort="15" velocity="2.09" lower="${-3.75 + safety_offset}" upper="${2.18 - safety_offset}"/>   <!--Theoretical limit +127/-215 , Real Limit +127/-215-->
      <!--safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-2.0943951 + 0.01}" soft_upper_limit="${2.0943951 - 0.01}" /-->
    </joint>

    <link name="${name}_7_link">
      <xacro:default_inertial/>
<!--
      <xacro:cylinder_inertial radius="0.03" length="0.035" mass="0.05">
        <origin xyz="0 0 0.06" rpy="0 0 0"/>
      </xacro:cylinder_inertial>
-->
      <visual>
        <origin xyz="0 0 0.06" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.03" length="0.035"/>
        </geometry>
        <material name="IPA/LightGrey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0.06" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.03" length="0.035"/>
        </geometry>
      </collision>
    </link>



    <!-- extensions -->
    <xacro:cob4_arm_gazebo name="${name}" />
    <xacro:cob4_arm_transmission name="${name}" />

    <!-- ros_control plugin -->
    <gazebo>
      <plugin name="${name}_ros_control" filename="libhwi_switch_gazebo_ros_control.so">
        <robotNamespace>${name}</robotNamespace>
        <filterJointsParam>joint_names</filterJointsParam>
      </plugin>
    </gazebo>

  </xacro:macro>

</robot>

