<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find desire_description)/urdf/base_desire/base.gazebo.xacro" />
  <xacro:include filename="$(find desire_description)/urdf/base_desire/base.transmission.xacro" />
  
  <!-- modify here for test -->
  <xacro:include filename="$(find cob_description)/urdf/sensors/sick_s300_laser.urdf.xacro"/>
  <xacro:include filename="$(find cob_description)/urdf/sensors/kinect.urdf.xacro" />

  <!-- DATA SOURCES -->
  <!-- all link offsets, CG, limits are obtained from Function Engineering spreadsheet 090224_link_data.xls unless stated otherwise -->
  <!-- all link geometry sizes are obtained from Function provided CAD model unless stated otherwise -->
  <!-- all simplified collision geometry are hand approximated from CAD model, sometimes from respective bounding boxes -->

  <property name="M_PI" value="3.1415926535897931" />

  <property name="caster_offset_x" value="0.235" />  <!--modify here-->
  <property name="caster_offset_y" value="0.185" />
  <property name="caster_offset_z" value="0.0282" />

  <property name="caster_wheel_offset_y" value="0.049" />
  <property name="wheel_length" value="0.034" />
  <property name="wheel_radius" value="0.074792" />   <!-- This is the 'effective' wheel radius. Wheel radius for uncompressed wheel is 0.079.  mp 20080801 -->

  <property name="base_cg_x" value="-0.061" />
  <property name="base_cg_y" value="0.0" />
  <property name="base_cg_z" value="0.293" />
  <property name="base_mass" value="116.0" />

  <!-- simplified box collision geometry for base -->
  <property name="base_size_x" value="0.8" />
  <property name="base_size_y" value="0.6" />
  <property name="base_size_z" value="0.23" />
  <property name="base_collision_size_z" value="0.04" />

  <!-- simplified box collision geometry for hokuyo laser -->
  <property name="base_laser_x" value="0.325" />
  <property name="base_laser_y" value="0.0" />
  <property name="base_laser_z" value="0.135" />
  <property name="base_laser_size_x" value="0.06" />
  <property name="base_laser_size_y" value="0.06" />
  <property name="base_laser_size_z" value="0.03" />
  <property name="base_laser_collision_offset_z" value="0.023" />

  <!--                                                      -->
  <!--           wheel                                      -->
  <!--                                                      -->
  <xacro:macro name="desire_wheel_v0" params="suffix parent reflect">

    <joint name="${parent}_${suffix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" />
      <limit effort="100" velocity="100"/> <!-- alpha tested effort and velocity limits -->
      <safety_controller  k_velocity="10" />
      <dynamics damping="0.0" friction="0.0" />
      <origin xyz="0 ${reflect*caster_wheel_offset_y} 0" rpy="0 0 0" />
      <parent link="${parent}_rotation_link"/>
      <child link="${parent}_${suffix}_wheel_link"/>
    </joint>

    <link name="${parent}_${suffix}_wheel_link">
      <inertial>
        <mass value="0.44036" />
        <origin xyz="0 0 0" />
        <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
                  iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://desire_description/meshes/base_desire/cob_wheel.stl" />
        </geometry>
        <material name="IPA/LightGrey" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" /> <!-- rotation because cyl. geom primitive has symmetry axis in +x direction -->
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
      </collision>
    </link>

    <!-- extensions -->
    <xacro:desire_wheel_gazebo_v0 parent="${parent}" suffix="${suffix}" />
    <xacro:desire_wheel_transmission_v0 parent="${parent}" suffix="${suffix}" reflect="${reflect}" />

  </xacro:macro>

  <!-- Macro for Caster hub only -->
  <xacro:macro name="desire_caster_hub_v0" params="suffix parent *origin ref_position" >
    <joint name="${suffix}_rotation_joint" type="continuous">
      <axis xyz="0 0 1" />
      <limit effort="100" velocity="100"/> <!-- alpha tested velocity and effort limits -->
      <safety_controller  k_velocity="10" />
      <calibration rising="${ref_position}" />
      <dynamics damping="0.0" friction="0.0" />
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${suffix}_rotation_link" />
    </joint>
    
    <link name="${suffix}_rotation_link">
      <inertial>
        <mass value="3.473082"/>
        <origin xyz="0 0 0.07" />
        <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
                  iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://desire_description/meshes/base_desire/caster.stl" />
        </geometry>
        <material name="IPA/DarkGrey" />
      </visual>
      <collision>
        <origin xyz="0 0 0.07" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.192 0.164 0.013" />
        </geometry>
      </collision>
    </link>

    <!-- extensions -->
    <xacro:desire_caster_transmission_v0 suffix="${suffix}" />
  </xacro:macro>

  <xacro:macro name="desire_caster_v0" params="suffix parent *origin ref_position">

    <xacro:desire_caster_hub_v0 parent="${parent}" suffix="${suffix}_caster"
                             ref_position="${ref_position}" >
      <insert_block name="origin" />
    </xacro:desire_caster_hub_v0>

    <!-- wheel macros -->
    <xacro:desire_wheel_v0 parent="${suffix}_caster" suffix="l" reflect="1" />
    <xacro:desire_wheel_v0 parent="${suffix}_caster" suffix="r" reflect="-1" />

    <!-- extensions -->
    <xacro:desire_caster_gazebo_v0 suffix="${suffix}" />
  </xacro:macro>


  <!-- The xacro macro xacro:desire_base contains: base, casters and wheels -->
  <!--xacro:macro name="desire_base_v0" params="name"-->
  <xacro:macro name="desire_base" params="name">
    <link name="${name}_link">
      <inertial>
        <mass value="${base_mass}" />
        <origin xyz="${base_cg_x} ${base_cg_y} ${base_cg_z}" />
        <inertia ixx="5.652232699207" ixy="-0.009719934438" ixz="1.293988226423"
                 iyy="5.669473158652" iyz="-0.007379583694" izz="3.683196351726" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://desire_description/meshes/base_desire/base.stl"/>
        </geometry> 
        <material name="IPA/DarkGrey" />
      </visual>
      <collision>
        <!-- represent base collision with a simple rectangular model, positioned by base_size_z s.t. top
             surface of the collision box matches the top surface of the PR2 base -->
        <origin xyz="0 0 ${base_size_z-base_collision_size_z/2}" rpy="0 0 0" />
        <geometry>
          <box size="${base_size_x} ${base_size_y} ${base_collision_size_z}" />
        </geometry>
      </collision>
    </link>

    <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin,
         navigation stack dedpends on this frame -->
    <link name="${name}_footprint"/>

    <joint name="${name}_footprint_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <child link="${name}_link" />
      <parent link="${name}_footprint"/>
    </joint>

    <!--modify here for test: front,base and top lasers -->
    <!-- base laser front -->
    <xacro:sick_s300_laser_v0 name="${name}_laser_front" parent="${name}" ros_topic="scan_front_raw" update_rate="10" min_angle="-2.3562" max_angle="2.3562" >
      <origin xyz="${base_laser_x} ${base_laser_y} ${base_laser_z}" rpy="${M_PI} 0 0" />
    </xacro:sick_s300_laser_v0>

    <!-- base laser rear -->
    <xacro:sick_s300_laser_v0 name="${name}_laser_rear" parent="${name}" ros_topic="scan_rear_raw" update_rate="10" min_angle="-2.3562" max_angle="2.3562" >
      <origin xyz="${-base_laser_x} ${base_laser_y} ${base_laser_z}" rpy="${M_PI} 0 ${M_PI}" />
    </xacro:sick_s300_laser_v0>

     <!-- cam3d -->
     <xacro:cob_kinect_v0 name="head_cam3d" ros_topic="cam3d" parent="base_link">
      <origin xyz="0.40 0 1.4246" rpy="0 0 0" />
     </xacro:cob_kinect_v0>


    <!-- all four caster macros -->
    <xacro:desire_caster_v0 suffix="fl" parent="${name}_link" ref_position="${cal_caster_fl - M_PI/4}" >
      <origin xyz="${caster_offset_x} ${caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
    </xacro:desire_caster_v0>
    <xacro:desire_caster_v0 suffix="fr" parent="${name}_link" ref_position="${cal_caster_fr - M_PI/4}" >
      <origin xyz="${caster_offset_x} ${-caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
    </xacro:desire_caster_v0>
    <xacro:desire_caster_v0 suffix="bl" parent="${name}_link" ref_position="${cal_caster_bl - M_PI / 4 + M_PI}" >
      <origin xyz="${-caster_offset_x} ${caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
    </xacro:desire_caster_v0>
    <xacro:desire_caster_v0 suffix="br" parent="${name}_link" ref_position="${cal_caster_br - M_PI / 4 + M_PI}"  >
      <origin xyz="${-caster_offset_x} ${-caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
    </xacro:desire_caster_v0>

    <!-- gazebo extensions -->
    <xacro:desire_base_gazebo_v0 name="${name}" />

  </xacro:macro>

</robot>
