<?xml version="1.0"?>
<package format="3">
  <name>cob_common</name>
  <version>0.8.12</version>
  <description>
    The cob_common stack hosts common packages used within the Care-O-bot repository, such as utility packages or common message and service definitions.
  </description>
  <license>Apache-2.0</license>
  <url type="website">http://ros.org/wiki/cob_common</url>
  <maintainer email="benjamin.maidel@4am-robotics.com">Benjamin Maidel</maintainer>
  <maintainer email="denis.lehmann@4am-robotics.com">Denis Lehmann</maintainer>
  <maintainer email="felixmessmer@gmail.com">Felix Messmer</maintainer>
  
  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <!-- List dependencies on the subpackages -->
  <exec_depend>cob_actions</exec_depend>
  <exec_depend>cob_msgs</exec_depend>
  <exec_depend>cob_srvs</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

</package>
